# Pandas  - Vaibhav Kumar , RollNo 19

In [1]:
import pandas as pd
import numpy as np

In [2]:
# create vector as a row
vector_row=np.array([1,2,3])

In [3]:
# create vector as a column
vector_column=np.array([[1],[2],[3]])

In [4]:
vector_row

array([1, 2, 3])

In [5]:
vector_column

array([[1],
       [2],
       [3]])

**Creating a matrix** 

In [6]:
from scipy import sparse

**only non zero elements will be stored in sparse matrix**

In [7]:
matrix=np.array([[0,0], 
               [0,1],
               [3,0]])

#create compressed sparse row (CSR) Matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [8]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [9]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [10]:
print(matrix_sparse) # it is giving the position , means 1 is it location 1st row 1st col , 
# and 3 is in locaiton 2nd row 1st col 

  (1, 1)	1
  (2, 0)	3


In [11]:
#create a large matrix
martix_large=np.array([[0,0,0,0,0,0,0,0],
                      [5,3,0,0,0,0,0,0],
                      [0,0,0,8,0,0,0,0],
                      [0,4,0,0,0,1,0,69]])

In [12]:
#create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(martix_large)


In [13]:
#view larger sparse matrix
print(matrix_large_sparse)

  (1, 0)	5
  (1, 1)	3
  (2, 3)	8
  (3, 1)	4
  (3, 5)	1
  (3, 7)	69


In [14]:
#create 3x3 matrix
matrix=np.array([[1,2,3],
               [4,5,6],
                [7,6,9]])

In [15]:
#finding maximum element in each column
np.max(matrix,axis=0)

array([7, 6, 9])

In [16]:
#finding maximum element in each row
np.max(matrix,axis=1)

array([3, 6, 9])

In [17]:
#return mean
np.mean(matrix)

4.777777777777778

In [18]:
#finding variance
np.var(matrix)

5.728395061728396

In [19]:
#finding standard deviation
np.std(matrix)

2.3934065809486684

# Reshaping of Array

In [20]:
#create 4x3 matrix
matrix=np.array([[1,2,3],
                [4,5,6],
                [6,7,8,],
                [6,54,7]])

In [21]:
#reshaping matrix in 2x6 matrix
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  6, 54,  7]])

In [22]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  6,  7,  8,  6, 54,  7]])

In [23]:
matrix.size

12

In [24]:
matrix.reshape(matrix.size)

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  6, 54,  7])

In [25]:
#TRANSPOSE OF MATRIX
matrix.T

array([[ 1,  4,  6,  6],
       [ 2,  5,  7, 54],
       [ 3,  6,  8,  7]])

In [26]:
#TRANSPOSE A VECTOR
np.array([1,2,3,4,5,6,7]).T

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#TRANSPOSE ROW VECTOR
np.array([[1,2,3,4,5,6,7]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [28]:
#FLATTEN MATRIX
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  6, 54,  7])

In [29]:
#Return Diagonal Elements
# need a NxN matrix to show result properly
#here we have 4x3 matrix that's why we are getting 3 elements only
matrix.diagonal()

array([1, 5, 8])

In [30]:
c= np.array([1,2,np.nan,4,5])
c # if we take nan value it will automaticly take floating point number

array([ 1.,  2., nan,  4.,  5.])

In [31]:
np.isnan(c) # it will give nan value if there as TRUE other FALSE

array([False, False,  True, False, False])

In [32]:
np.mean(c) 

nan

In [33]:
# if any data contains nan value and we need MEAN VALUE we need to use this 
a=np.mean(c[~np.isnan(c)])

In [34]:
a

3.0

In [35]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 6, 54,  7]])

In [36]:
# astype() is to convert any datatype to another
a=matrix.astype('float')

In [37]:
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 6.,  7.,  8.],
       [ 6., 54.,  7.]])

# Important **********

In [38]:
a[0][0]=np.nan


In [39]:
a[1][1]=np.inf # infinity value

In [40]:
a

array([[nan,  2.,  3.],
       [ 4., inf,  6.],
       [ 6.,  7.,  8.],
       [ 6., 54.,  7.]])

In [41]:
np.isinf(a) # checking for a infinity value

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [42]:
np.isnan(a)

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [44]:
flag=np.isinf(a)|np.isnan(a) # pipe fn is to check multiple conditions at a time 

In [45]:
flag

array([[ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [57]:
flag

array([[ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

# DATA CLEANING

In [46]:
a[flag]

array([nan, inf])

In [47]:
a[flag]=0 #replacing flags value to zero 
# not a right way to do

In [48]:
a

array([[ 0.,  2.,  3.],
       [ 4.,  0.,  6.],
       [ 6.,  7.,  8.],
       [ 6., 54.,  7.]])

In [50]:
dict={'A':100,'B':200,'C':300,'D':400}
z1=pd.Series(dict)
z1

A    100
B    200
C    300
D    400
dtype: int64

In [54]:
z2=pd.Series([10,20,30,40],'A B D E'.split())

In [55]:
'A B C D'.split()

['A', 'B', 'C', 'D']

In [56]:
z2

A    10
B    20
D    30
E    40
dtype: int64

In [57]:
z1+z2

A    110.0
B    220.0
C      NaN
D    430.0
E      NaN
dtype: float64

# Slicing in Series


In [58]:
z1

A    100
B    200
C    300
D    400
dtype: int64

In [59]:
z1['A':'C']

A    100
B    200
C    300
dtype: int64

In [60]:
type(z1['A':'C'])

pandas.core.series.Series

In [61]:
z1[['A','C']]

A    100
C    300
dtype: int64

In [62]:
#using default index values
z1[[0,1]]

A    100
B    200
dtype: int64

## Indexing

In [63]:
# .iloc does integer based indexing 
z1.iloc[2] # need to specify the integer

300

In [64]:
#loc does label based indexing
z1.loc['A'] # here we need to specify the label instead of integer

100


## OPERATIONS


In [65]:
z1>100

A    False
B     True
C     True
D     True
dtype: bool

In [66]:
z1[z1>100] #condition

B    200
C    300
D    400
dtype: int64

In [67]:
b=[True,False,True,False]
z1[b]
# here where ever there is true it will return


A    100
C    300
dtype: int64

### BROADCASTING

In [68]:
z1+200

A    300
B    400
C    500
D    600
dtype: int64

### Ordering on Series

In [69]:
#sort_values()  func to perform sorting 
z1.sort_values(ascending=False)

D    400
C    300
B    200
A    100
dtype: int64

In [70]:
z1.sort_values(ascending=False).index[1]

'C'

In [71]:
z1 # no change in data

A    100
B    200
C    300
D    400
dtype: int64

In [72]:
# if we want to change the data permanently use 
# inplace=True
z1.sort_values(ascending=False,inplace=True)

In [73]:
z1

D    400
C    300
B    200
A    100
dtype: int64

## aggregation on series


In [74]:
z1.mean()

250.0

In [75]:
z1.sum()

1000

In [76]:
z1.max()

400

In [77]:
z1.min() 

100

In [79]:
z1.idxmax()

'D'

### Series with two Column

In [80]:
data_1={'Column1':pd.Series([2,3,4,5],['a b c d'.split()]),
       'Column2':pd.Series([20,30,40,50],['A B C D'.split()])}

In [81]:
data_1

{'Column1': a    2
 b    3
 c    4
 d    5
 dtype: int64,
 'Column2': A    20
 B    30
 C    40
 D    50
 dtype: int64}

# DATA FRAME

In [82]:
rand_mat=np.random.randn(5,4)
rand_mat

array([[-1.74540593,  0.07421877,  0.33358931, -0.47758962],
       [ 0.28027289, -0.82350207,  0.39630927, -0.8463551 ],
       [ 1.15484762, -2.49408557,  0.21734834, -0.85388345],
       [-0.32731119, -1.51705037,  0.05424037,  1.12742118],
       [-1.67727736,  0.07928247,  0.45841675, -0.63848852]])

In [83]:
df = pd.DataFrame(rand_mat,index='A B C D E'.split(),
columns = 'W X Y Z'.split())

In [84]:
df

W         X         Y         Z
A -1.745406  0.074219  0.333589 -0.477590
B  0.280273 -0.823502  0.396309 -0.846355
C  1.154848 -2.494086  0.217348 -0.853883
D -0.327311 -1.517050  0.054240  1.127421
E -1.677277  0.079282  0.458417 -0.638489

## Selection and Indexing

In [85]:
df['W']

A   -1.745406
B    0.280273
C    1.154848
D   -0.327311
E   -1.677277
Name: W, dtype: float64

In [86]:
df[['W','Z']]

W         Z
A -1.745406 -0.477590
B  0.280273 -0.846355
C  1.154848 -0.853883
D -0.327311  1.127421
E -1.677277 -0.638489

In [88]:
df[['W','X']]

W         X
A -1.745406  0.074219
B  0.280273 -0.823502
C  1.154848 -2.494086
D -0.327311 -1.517050
E -1.677277  0.079282

In [89]:
df.W #NOT RECOMENDDED 

A   -1.745406
B    0.280273
C    1.154848
D   -0.327311
E   -1.677277
Name: W, dtype: float64

In [91]:
df.iloc[2]

W    1.154848
X   -2.494086
Y    0.217348
Z   -0.853883
Name: C, dtype: float64

### ADDING A ROW

In [92]:
df.loc['F']=df.loc['A']+df.loc['B']

In [93]:
df

W         X         Y         Z
A -1.745406  0.074219  0.333589 -0.477590
B  0.280273 -0.823502  0.396309 -0.846355
C  1.154848 -2.494086  0.217348 -0.853883
D -0.327311 -1.517050  0.054240  1.127421
E -1.677277  0.079282  0.458417 -0.638489
F -1.465133 -0.749283  0.729899 -1.323945

In [94]:
# if we want to reset the indexes as Default
df.reset_index()

index         W         X         Y         Z
0     A -1.745406  0.074219  0.333589 -0.477590
1     B  0.280273 -0.823502  0.396309 -0.846355
2     C  1.154848 -2.494086  0.217348 -0.853883
3     D -0.327311 -1.517050  0.054240  1.127421
4     E -1.677277  0.079282  0.458417 -0.638489
5     F -1.465133 -0.749283  0.729899 -1.323945

In [95]:
#for changing the index names
newindex = 'DEL UP UK TN AP KL'.split()

In [96]:
df['States']=newindex # added a column

In [97]:
df

W         X         Y         Z States
A -1.745406  0.074219  0.333589 -0.477590    DEL
B  0.280273 -0.823502  0.396309 -0.846355     UP
C  1.154848 -2.494086  0.217348 -0.853883     UK
D -0.327311 -1.517050  0.054240  1.127421     TN
E -1.677277  0.079282  0.458417 -0.638489     AP
F -1.465133 -0.749283  0.729899 -1.323945     KL

In [98]:
# now we have to replace abcdef to states values
df.set_index('States',inplace=True)

In [99]:
df

W         X         Y         Z
States                                        
DEL    -1.745406  0.074219  0.333589 -0.477590
UP      0.280273 -0.823502  0.396309 -0.846355
UK      1.154848 -2.494086  0.217348 -0.853883
TN     -0.327311 -1.517050  0.054240  1.127421
AP     -1.677277  0.079282  0.458417 -0.638489
KL     -1.465133 -0.749283  0.729899 -1.323945

### Multi -Index and Index Hierarchy

In [103]:
# Index levels
outside=['North','North','North','South','South','South']
inside=newindex

In [104]:
hier_index=list(zip(outside,inside))

In [105]:
hier_index

[('North', 'DEL'),
 ('North', 'UP'),
 ('North', 'UK'),
 ('South', 'TN'),
 ('South', 'AP'),
 ('South', 'KL')]

In [106]:
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [107]:
hier_index

MultiIndex([('North', 'DEL'),
            ('North',  'UP'),
            ('North',  'UK'),
            ('South',  'TN'),
            ('South',  'AP'),
            ('South',  'KL')],
           )

In [108]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
North DEL -1.558007  0.849948
      UP   1.059091  0.575323
      UK   1.727948  0.269926
South TN   0.348608  1.617945
      AP  -0.333769 -0.129678
      KL  -0.484702 -0.267028

In [109]:
# now we can fetch the data according to hierarcy 
df.loc['North']

A         B
DEL -1.558007  0.849948
UP   1.059091  0.575323
UK   1.727948  0.269926

In [110]:
df.loc['North'].loc['DEL']

A   -1.558007
B    0.849948
Name: DEL, dtype: float64

In [111]:
#index not been assigned to any names
df.index.names

FrozenList([None, None])

In [112]:
df.index.names=['Region','States']

In [113]:
#Return Cross-section from the series/dataframe
df.xs('North')

A         B
States                    
DEL    -1.558007  0.849948
UP      1.059091  0.575323
UK      1.727948  0.269926

In [115]:
outside=['North','North','North','South','South','South']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [116]:
df=pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df.index.names=['Region','Num']
df

A         B
Region Num                    
North  1    0.751418  1.308372
       2    0.778414 -0.481113
       3    1.521295  0.002127
South  1   -0.917190 -2.664525
       2   -0.025975 -1.221268
       3    1.980576 -1.036305

In [118]:
df.xs(['North',1])

C:\Users\studentadmin\AppData\Local\Temp\ipykernel_9256\453744059.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['North',1])


A    0.751418
B    1.308372
Name: (North, 1), dtype: float64

In [119]:
df.xs(1,level='Num')

A         B
Region                    
North   0.751418  1.308372
South  -0.917190 -2.664525