In [1]:
import numpy as np

In [2]:
x = [1, 2, 3, 4, 5]

In [3]:
x

[1, 2, 3, 4, 5]

In [4]:
type(x)

list

In [5]:
y = np.array([1, 2, 3, 4, 5, 6])

In [6]:
type(y)

numpy.ndarray

In [7]:
y = np.array((1, 2, 3, 4, 5, 6))

In [8]:
type(y)

numpy.ndarray

In [9]:
x = [1, 2, 'MCA', 89]

In [10]:
x

[1, 2, 'MCA', 89]

In [11]:
type(x)

list

In [14]:
y = np.array(x)

In [15]:
y

array(['1', '2', 'MCA', '89'], dtype='<U11')

In [17]:
y = np.linspace(start = 0, stop = 20, num = 10)

In [18]:
y

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [19]:
y = np.linspace(start = 1, stop = 20, num = 10)
y

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [20]:
y = np.linspace(start = 0, stop = 20, num = 10, endpoint = True)
y

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [21]:
y = np.linspace(start = 0, stop = 20, num = 10, endpoint = False)
y

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [22]:
y = np.linspace(start = 0, stop = 20, num = 10, endpoint = True, retstep = True)
y
# retstep  = True gives value of difference

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

In [23]:
y = np.linspace(start = 0, stop = 20, num = 10, endpoint = True, retstep = False)
y

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [24]:
d = np.arange(start = 1, stop = 10, step = 2)
d

array([1, 3, 5, 7, 9])

In [27]:
z = [[1,2,3],[5,6,7],[9,4,8]]
z

[[1, 2, 3], [5, 6, 7], [9, 4, 8]]

In [29]:
z = np.array([[1,2,3],[5,6,7],[9,4,8]])
z

array([[1, 2, 3],
       [5, 6, 7],
       [9, 4, 8]])

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.eye(4) 
# identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
x = np.array([0,1,2,3,4,5,6,7,8,9])

In [34]:
x.reshape(5,2)
# returns in the form of 5x2 array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
s = slice(2,7,2) 
# slicing - means cutting or taking some part of array(start, end, steps)

In [37]:
a[s]

array([2, 4, 6])

In [40]:
x[2:7:2]
# another method of slicing by specifying the start index, end index and steps

array([2, 4, 6])

In [41]:
x[-6:-2]

array([4, 5, 6, 7])

In [43]:
np.random.rand(5)

array([0.65191768, 0.63170174, 0.16458092, 0.54041149, 0.83601623])

In [44]:
np.random.rand(5,4)

array([[0.34697078, 0.97222764, 0.87993377, 0.49240731],
       [0.27294008, 0.46397675, 0.79554136, 0.45952246],
       [0.29100488, 0.35961183, 0.45371267, 0.89791418],
       [0.11906377, 0.00795854, 0.57834562, 0.33687606],
       [0.55787403, 0.75799445, 0.03237801, 0.84758035]])

In [45]:
np.random.rand(5)
# when call, it always generates random value

array([0.30983023, 0.39569294, 0.71793451, 0.34000124, 0.43750322])

In [46]:
np.random.rand(5,5)

array([[0.26096736, 0.85829436, 0.96284431, 0.70592686, 0.23070938],
       [0.01249787, 0.37407213, 0.68255972, 0.57997186, 0.85806732],
       [0.77303798, 0.99165703, 0.58648137, 0.85337211, 0.46624249],
       [0.82029882, 0.48013163, 0.8143992 , 0.73797926, 0.74873454],
       [0.34332778, 0.43485527, 0.44304165, 0.92551339, 0.54450973]])

In [47]:
np.random.randint(low =1, high =100)
# it will pick random value from 1 to 100

29

In [48]:
np.random.randint(low =1, high =100, size=10)
# using size, we can get multiple values

array([15,  8,  7, 77, 45, 11,  1, 65, 60, 42])

In [50]:
np.random.seed(40)
np.random.rand(4)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518])

In [53]:
np.random.seed(40)
np.random.rand(4)
#compare the outputs i.e. OUT[50] and OUT[53], after using seed function you get same random value every time you call random function

array([0.40768703, 0.05536604, 0.78853488, 0.28730518])

In [54]:
arr = np.arange(0, 10, 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [56]:
arr/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [61]:
slice_arr[:] = 500
slice_arr

array([500, 500, 500, 500, 500, 500])

In [62]:
arr

array([500, 500, 500, 500, 500, 500,   6,   7,   8,   9])

In [63]:
arr_copy = arr.copy()
#by using the copy function our actual array will not get changed
#it will crete a copy of actual array and performs changes to that array

In [64]:
arr_copy[:] = 1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [65]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
boo_arr = arr>4
boo_arr
# if arr>4 returns True else False

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [69]:
arr[boo_arr]
#only returns the true values i.e. arr>4

array([5, 6, 7, 8, 9])

In [70]:
arr[arr>5]

array([6, 7, 8, 9])

In [71]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [75]:
arr/0

C:\Users\studentadmin\AppData\Local\Temp\ipykernel_17856\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
C:\Users\studentadmin\AppData\Local\Temp\ipykernel_17856\4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [76]:
1/arr

C:\Users\studentadmin\AppData\Local\Temp\ipykernel_17856\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [77]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [78]:
arr.dtype

dtype('int32')

In [79]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [81]:
np.exp(arr)
# e^num

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [85]:
size = 100

In [86]:
x1 = range(size)
x1

range(0, 100)

In [87]:
y1 = range(size)
y1

range(0, 100)

In [93]:
%%timeit
[x1[i]*y1[i] for i in range(size)]

15.5 µs ± 193 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [96]:
x2 = np.arange(size)
y2 = np.arange(size)

In [97]:
%%timeit
x2*y2
#here computational is faster than the previous method 

372 ns ± 2.36 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [98]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
a_row = np.append(a, [[21,22,23]], axis=0)
a_row
#axis = 1 for column format and axis = 0 for row format

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23]])

In [101]:
a_col = np.array([34,35,36]).reshape(3,1)
a_col
#we need to reshape it to append it in the column format

array([[34],
       [35],
       [36]])

In [102]:
a_col1 = np.append(a, a_col, axis=1)
a_col1

array([[ 1,  2,  3, 34],
       [ 4,  5,  6, 35],
       [ 7,  8,  9, 36]])