In [2]:
import numpy as np

In [4]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b.shape

(3, 3)

In [6]:
b.size
#to check the number of elements in the array

9

In [7]:
b_ins = np.insert(b, 1,[15,13,15], axis=0)
b_ins
#to insert in the second column

array([[ 1,  2,  3],
       [15, 13, 15],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [8]:
b_ins2 = np.insert(b,2,[15,13,12], axis=1)
b_ins2

array([[ 1,  2, 15,  3],
       [ 4,  5, 13,  6],
       [ 7,  8, 12,  9]])

In [9]:
x = np.matrix('1,2,3;4,5,6;7,8,9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
x.shape

(3, 3)

In [11]:
x.size

9

In [13]:
x[2,1] = -5
x
# to change the element of 3rd row 2nd column

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -5,  9]])

In [14]:
x[1, :]
#to get the 2nd column in the matrix

matrix([[4, 5, 6]])

In [15]:
arr = np.array([[1,2,3], [4,5,6], [7,-8,9]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -8,  9]])

In [16]:
arr[1]

array([4, 5, 6])

In [17]:
# Matrix Mulitplication
x*x

matrix([[ 30,  -3,  42],
        [ 66,   3,  96],
        [ 50, -56,  72]])

In [18]:
# Array Multiplication
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])